from enum import Enum
import random

class EffectType(Enum):
    POISON = "poison"
    BURN = "burn"
    FREEZE = "freeze"
    STUN = "stun"
    BLEED = "bleed"
    CURSE = "curse"
    BLESS = "bless"
    REGENERATION = "regeneration"
    MANA_REGEN = "mana_regen"
    STRENGTH_BOOST = "strength_boost"
    AGILITY_BOOST = "agility_boost"
    INTELLIGENCE_BOOST = "intelligence_boost"
    VITALITY_BOOST = "vitality_boost"
    DEFENSE_BOOST = "defense_boost"
    CRIT_CHANCE_BOOST = "crit_chance_boost"
    DODGE_CHANCE_BOOST = "dodge_chance_boost"
    COOLDOWN_REDUCTION = "cooldown_reduction"
    EXPERIENCE_BOOST = "experience_boost"
    GOLD_BOOST = "gold_boost"
    PORTAL_CHANCE_BOOST = "portal_chance_boost"
    INSTANT_KILL = "instant_kill"
    STAT_BOOST = "stat_boost"
    SHADOW_DAMAGE_BOOST = "shadow_damage_boost"
    SHADOW_COOLDOWN_REDUCTION = "shadow_cooldown_reduction"
    SHADOW_EXTRACTION_BOOST = "shadow_extraction_boost"
    EXTRA_SHADOW = "extra_shadow"
    FIRE_DAMAGE_BOOST = "fire_damage_boost"
    FIRE_IMMUNITY = "fire_immunity"
    FIRE_BREATH = "fire_breath"
    HOLY_DAMAGE_BOOST = "holy_damage_boost"
    HEALING_BOOST = "healing_boost"
    CURSE_IMMUNITY = "curse_immunity"
    RESURRECTION = "resurrection"

class Effect:
    def __init__(self, effect_type, duration, power=1):
        self.type = effect_type
        self.duration = duration
        self.power = power
    
    def apply_effect(self, target):
        if self.type == EffectType.POISON:
            damage = self.power * 2
            target.take_damage(damage)
            return f"{target.username} takes {damage} poison damage!"
        
        elif self.type == EffectType.BURN:
            damage = self.power * 3
            target.take_damage(damage)
            return f"{target.username} takes {damage} burn damage!"
        
        elif self.type == EffectType.BLEED:
            damage = self.power * 2
            target.take_damage(damage)
            return f"{target.username} takes {damage} bleed damage!"
        
        elif self.type == EffectType.STUN:
            return f"{target.username} is stunned and cannot act!"
        
        elif self.type == EffectType.FREEZE:
            target.frozen = True
            return f"{target.username} is frozen!"
        
        elif self.type == EffectType.CURSE:
            target.defense = int(target.defense * 0.8)  # Reduce defense by 20%
            return f"{target.username}'s defense is reduced!"
        
        elif self.type == EffectType.BLESS:
            target.defense = int(target.defense * 1.2)  # Increase defense by 20%
            return f"{target.username}'s defense is increased by blessing!"
        
        elif self.type == EffectType.REGENERATION:
            target.health += self.power
            return f"{target.username}'s health is regenerated by {self.power}!"
        
        elif self.type == EffectType.MANA_REGEN:
            target.mana += self.power
            return f"{target.username}'s mana is regenerated by {self.power}!"
        
        elif self.type == EffectType.STRENGTH_BOOST:
            target.strength = int(target.strength * 1.2)  # Increase strength by 20%
            return f"{target.username}'s strength is increased!"
        
        elif self.type == EffectType.AGILITY_BOOST:
            target.agility = int(target.agility * 1.2)  # Increase agility by 20%
            return f"{target.username}'s agility is increased!"
        
        elif self.type == EffectType.INTELLIGENCE_BOOST:
            target.intelligence = int(target.intelligence * 1.2)  # Increase intelligence by 20%
            return f"{target.username}'s intelligence is increased!"
        
        elif self.type == EffectType.VITALITY_BOOST:
            target.health += self.power
            return f"{target.username}'s health is increased by {self.power}!"
        
        elif self.type == EffectType.DEFENSE_BOOST:
            target.defense = int(target.defense * 1.2)  # Increase defense by 20%
            return f"{target.username}'s defense is increased!"
        
        elif self.type == EffectType.CRIT_CHANCE_BOOST:
            target.crit_chance += self.power
            return f"{target.username}'s critical chance is increased by {self.power}%!"
        
        elif self.type == EffectType.DODGE_CHANCE_BOOST:
            target.dodge_chance += self.power
            return f"{target.username}'s dodge chance is increased by {self.power}%!"
        
        elif self.type == EffectType.COOLDOWN_REDUCTION:
            target.cooldown_reduction += self.power
            return f"{target.username}'s cooldown reduction is increased by {self.power}%!"
        
        elif self.type == EffectType.EXPERIENCE_BOOST:
            target.experience += self.power
            return f"{target.username}'s experience is increased by {self.power}!"
        
        elif self.type == EffectType.GOLD_BOOST:
            target.gold += self.power
            return f"{target.username}'s gold is increased by {self.power}!"
        
        elif self.type == EffectType.PORTAL_CHANCE_BOOST:
            target.portal_chance += self.power
            return f"{target.username}'s portal chance is increased by {self.power}%!"
        
        elif self.type == EffectType.INSTANT_KILL:
            target.health = 0
            return f"{target.username} is instantly killed!"
        
        elif self.type == EffectType.STAT_BOOST:
            target.strength = int(target.strength * 1.2)  # Increase strength by 20%
            target.agility = int(target.agility * 1.2)  # Increase agility by 20%
            target.intelligence = int(target.intelligence * 1.2)  # Increase intelligence by 20%
            target.vitality = int(target.vitality * 1.2)  # Increase vitality by 20%
            target.defense = int(target.defense * 1.2)  # Increase defense by 20%
            return f"{target.username}'s stats are boosted!"
        
        elif self.type == EffectType.SHADOW_DAMAGE_BOOST:
            damage = self.power * 2
            target.take_damage(damage)
            return f"{target.username} takes {damage} shadow damage!"
        
        elif self.type == EffectType.SHADOW_COOLDOWN_REDUCTION:
            target.shadow_cooldown_reduction += self.power
            return f"{target.username}'s shadow cooldown reduction is increased by {self.power}%!"
        
        elif self.type == EffectType.SHADOW_EXTRACTION_BOOST:
            target.shadow_extraction += self.power
            return f"{target.username}'s shadow extraction is increased by {self.power}!"
        
        elif self.type == EffectType.EXTRA_SHADOW:
            target.shadow_strength += self.power
            return f"{target.username}'s shadow strength is increased by {self.power}!"
        
        elif self.type == EffectType.FIRE_DAMAGE_BOOST:
            damage = self.power * 2
            target.take_damage(damage)
            return f"{target.username} takes {damage} fire damage!"
        
        elif self.type == EffectType.FIRE_IMMUNITY:
            target.fire_immunity = True
            return f"{target.username} is immune to fire!"
        
        elif self.type == EffectType.FIRE_BREATH:
            damage = self.power * 3
            target.take_damage(damage)
            return f"{target.username} takes {damage} fire breath damage!"
        
        elif self.type == EffectType.HOLY_DAMAGE_BOOST:
            damage = self.power * 2
            target.take_damage(damage)
            return f"{target.username} takes {damage} holy damage!"
        
        elif self.type == EffectType.HEALING_BOOST:
            target.health += self.power
            return f"{target.username}'s health is healed by {self.power}!"
        
        elif self.type == EffectType.CURSE_IMMUNITY:
            target.curse_immunity = True
            return f"{target.username} is immune to curses!"
        
        elif self.type == EffectType.RESURRECTION:
            target.health = target.max_health
            return f"{target.username} is resurrected!"
        
        return None
    
    def tick(self):
        self.duration -= 1
        return self.duration > 0

class EffectManager:
    def __init__(self):
        self.effects = []
    
    def add_effect(self, effect):
        # Check if effect already exists
        for existing_effect in self.effects:
            if existing_effect.type == effect.type:
                # Refresh duration and update power if new effect is stronger
                if effect.power > existing_effect.power:
                    existing_effect.power = effect.power
                existing_effect.duration = max(existing_effect.duration, effect.duration)
                return
        
        self.effects.append(effect)
    
    def remove_effect(self, effect_type):
        self.effects = [e for e in self.effects if e.type != effect_type]
    
    def process_effects(self, target):
        results = []
        effects_to_remove = []
        
        for effect in self.effects:
            result = effect.apply_effect(target)
            if result:
                results.append(result)
            
            if not effect.tick():
                effects_to_remove.append(effect)
        
        for effect in effects_to_remove:
            self.effects.remove(effect)
        
        return results
    
    def get_active_effects(self):
        return [(effect.type.value, effect.duration) for effect in self.effects]
    
    def has_effect(self, effect_type):
        return any(effect.type == effect_type for effect in self.effects) 